<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>..\..\assets\icons\app-icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ClipboardManager.Application\ClipboardManager.Application.csproj" />
    <ProjectReference Include="..\ClipboardManager.Domain\ClipboardManager.Domain.csproj" />
    <ProjectReference Include="..\ClipboardManager.Infrastructure\ClipboardManager.Infrastructure.csproj" />
    <ProjectReference Include="..\ClipboardManager.Shared\ClipboardManager.Shared.csproj" />
  </ItemGroup>
</Project>
