<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ClipboardManager.Domain\ClipboardManager.Domain.csproj" />
    <ProjectReference Include="..\ClipboardManager.Shared\ClipboardManager.Shared.csproj" />
  </ItemGroup>
</Project>
